### ISSUE TITLE
tvheadend for Apollo Lake and DSM 7

### ISSUE THREAD

**Issue by cO5Mo2** [th0ma7/synology#10]
Hello,

First of all I'd like to thank for great work. So far everything works fine on my synology nas except that I cant find the tvheadend version for dsm 7 and apollo lake.

Could you point ne in the right direction?

Thanks a lot

**Comment by th0ma7** [comment]
Work on this is still continuing in order to make the package to be compatible with DSM7.

Once the following PR gets merged I should be able to provide a new experimental package in [here](https://github.com/th0ma7/synology/tree/master/packages/dsm7-beta).
* https://github.com/SynoCommunity/spksrc/pull/4579
* https://github.com/SynoCommunity/spksrc/pull/4545
* https://github.com/SynoCommunity/spksrc/pull/4576

**Comment by th0ma7** [comment]
Beta DSM7 packages upcoming at https://github.com/th0ma7/synology/tree/master/packages/dsm7-beta
(a few left building and upcoming)

**Comment by th0ma7** [comment]
Package now available, closing issue.
