### ISSUE TITLE
FFmpeg on DSM 7.0 RC

### ISSUE THREAD

**Issue by Cadkey** [th0ma7/synology#11]
DS920+
ffmpeg for DSM 7.0 beta x64 doesn't work on my DS920+ DSM 7.0 RC

**Comment by mitchoklemen** [comment]
True that :)

**Comment by th0ma7** [comment]
Work on this is still continuing in order to make the package to be compatible with DSM7.
(was paused in the past month due to other priorities)

Once the following PR gets merged I should be able to provide a new experimental package in [here](https://github.com/th0ma7/synology/tree/master/packages/dsm7-beta).
* https://github.com/SynoCommunity/spksrc/pull/4579
* https://github.com/SynoCommunity/spksrc/pull/4545
* https://github.com/SynoCommunity/spksrc/pull/4576

**Comment by th0ma7** [comment]
New beta packages now available.
https://github.com/th0ma7/synology/tree/master/packages/dsm7-beta

**Comment by Cadkey** [comment]
Merci pour la mise à jour.
Je suis revenu en DSM6 suite aux nombreux paquets qui étaient cassés en DSM 7.0 RC.
Ffmpeg 4.3.2 fonctionne sur mon 920+
J'attends la version 7 Finale pour migrer.
Merci

**Comment by th0ma7** [comment]
paquet pour DSM7 maintenant rendu disponible, fermeture du bug.
